version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: eurus_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Manish
      MONGO_INITDB_ROOT_PASSWORD: My8572839479#
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: eurus_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Manish
      ME_CONFIG_MONGODB_ADMINPASSWORD: My8572839479#
      ME_CONFIG_MONGODB_URL: mongodb://Manish:My8572839479#@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: Manish
      ME_CONFIG_BASICAUTH_PASSWORD: My8572839479#
    depends_on:
      - mongodb

volumes:
  mongo_data:
